graph TB
    subgraph "When to Create Associations"
        Store["store_memory()"]
        
        CorrectionCheck{"Is this a<br/>user correction?"}
        BugFixCheck{"Is this a<br/>bug fix?"}
        DecisionCheck{"Is this a<br/>decision?"}
        
        SearchRelated["recall_memory()<br/>find related"]
        
        InvalidatedBy["associate_memories()<br/>type: INVALIDATED_BY<br/>strength: 0.9"]
        
        DerivedFrom["associate_memories()<br/>type: DERIVED_FROM<br/>strength: 0.8"]
        
        PrefersOver["associate_memories()<br/>type: PREFERS_OVER<br/>strength: 0.85"]
    end
    
    Store --> CorrectionCheck
    CorrectionCheck -->|Yes| SearchRelated
    CorrectionCheck -->|No| BugFixCheck
    
    BugFixCheck -->|Yes| SearchRelated
    BugFixCheck -->|No| DecisionCheck
    
    DecisionCheck -->|Yes| SearchRelated
    
    SearchRelated --> InvalidatedBy
    SearchRelated --> DerivedFrom
    SearchRelated --> PrefersOver