stateDiagram-v2
    [*] --> Created: store_memory
    Created --> Recalled: recall_memory
    Recalled --> Updated: update_memory
    Updated --> Recalled: recall_memory
    Created --> Associated: associate_memories
    Associated --> Recalled: recall_memory
    Recalled --> Deleted: delete_memory
    Updated --> Deleted: delete_memory
    Associated --> Deleted: delete_memory
    Deleted --> [*]
    
    Created --> Monitored: check_database_health
    Recalled --> Monitored: check_database_health
    Updated --> Monitored: check_database_health
    Associated --> Monitored: check_database_health